## Step 1: Extraction

## 1: Importing necessary libaries

In [4]:
import requests
import pandas as pd
import psycopg2 
import json

## 2: Carry out Extraction

In [37]:

url = "https://api.rentcast.io/v1/properties/random?limit=500"


headers = {
    "accept": "application/json",
    "X-Api-Key": "b474e2153f5945ccb0b0f0cf5ae6aa6e"
}

response = requests.get(url, headers=headers)

In [32]:
print(response.json())

[{'id': '5500-Grand-Lake-Dr,-San-Antonio,-TX-78244', 'formattedAddress': '5500 Grand Lake Dr, San Antonio, TX 78244', 'addressLine1': '5500 Grand Lake Dr', 'addressLine2': None, 'city': 'San Antonio', 'state': 'TX', 'zipCode': '78244', 'county': 'Bexar', 'latitude': 29.475962, 'longitude': -98.351442, 'propertyType': 'Single Family', 'bedrooms': 3, 'bathrooms': 2, 'squareFootage': 1878, 'lotSize': 8850, 'yearBuilt': 1973, 'assessorID': '05076-103-0500', 'legalDescription': 'CB 5076A BLK 3 LOT 50', 'subdivision': 'WOODLAKE', 'zoning': 'RH', 'lastSaleDate': '2024-11-18T00:00:00.000Z', 'hoa': {'fee': 175}, 'features': {'architectureType': 'Contemporary', 'cooling': True, 'coolingType': 'Central', 'exteriorType': 'Wood', 'fireplace': True, 'fireplaceType': 'Masonry', 'floorCount': 1, 'foundationType': 'Slab / Mat / Raft', 'garage': True, 'garageSpaces': 2, 'garageType': 'Garage', 'heating': True, 'heatingType': 'Forced Air', 'pool': True, 'poolType': 'Concrete', 'roofType': 'Asphalt', 'roomCount': 5, 'unitCount': 1, 'viewType': 'City'}, 'taxAssessments': {'2017': {'year': 2017, 'value': 134880, 'land': 18760, 'improvements': 116120}, '2018': {'year': 2018, 'value': 126510, 'land': 18760, 'improvements': 107750}, '2019': {'year': 2019, 'value': 135430, 'land': 23450, 'improvements': 111980}, '2020': {'year': 2020, 'value': 142610, 'land': 23450, 'improvements': 119160}, '2021': {'year': 2021, 'value': 163440, 'land': 45050, 'improvements': 118390}, '2022': {'year': 2022, 'value': 197600, 'land': 49560, 'improvements': 148040}, '2023': {'year': 2023, 'value': 225790, 'land': 59380, 'improvements': 166410}, '2024': {'year': 2024, 'value': 216513, 'land': 59380, 'improvements': 157133}}, 'propertyTaxes': {'2017': {'year': 2017, 'total': 3064}, '2018': {'year': 2018, 'total': 2890}, '2019': {'year': 2019, 'total': 2984}, '2020': {'year': 2020, 'total': 3023}, '2021': {'year': 2021, 'total': 3455}, '2022': {'year': 2022, 'total': 4091}, '2023': {'year': 2023, 'total': 4201}}, 'history': {'2004-06-16': {'event': 'Sale', 'date': '2004-06-16T00:00:00.000Z', 'price': 95000}, '2017-10-19': {'event': 'Sale', 'date': '2017-10-19T00:00:00.000Z'}, '2024-11-18': {'event': 'Sale', 'date': '2024-11-18T00:00:00.000Z'}}, 'owner': {'names': ['Rolando Villarreal', 'Maria Teresa Loredo Villarreal'], 'type': 'Individual', 'mailingAddress': {'id': '5500-Grand-Lake-Dr,-San-Antonio,-TX-78244', 'formattedAddress': '5500 Grand Lake Dr, San Antonio, TX 78244', 'addressLine1': '5500 Grand Lake Dr', 'addressLine2': None, 'city': 'San Antonio', 'state': 'TX', 'zipCode': '78244'}}, 'ownerOccupied': True}]

In [38]:
data = response.json()
file_name = 'real_estate.json'
with open (file_name, 'w') as file:
    json.dump(data, file, indent=4)

In [40]:
real_estate_df = pd.read_json('real_estate.json')
real_estate_df.head()

,id,formattedAddress,addressLine1,addressLine2,city,state,zipCode,county,latitude,longitude,...,zoning,lastSaleDate,lastSalePrice,features,taxAssessments,propertyTaxes,history,owner,ownerOccupied,hoa
0,"1680-Ne-159th-St,-North-Miami-Beach,-FL-33162","1680 Ne 159th St, North Miami Beach, FL 33162",1680 Ne 159th St,None,North Miami Beach,FL,33162,Miami-Dade,25.921956,-80.166327,...,"0500:SGL FAM,1201-1400 SQ",2002-08-26T00:00:00.000Z,99000.0,"{'exteriorType': 'Concrete Block', 'floorCount...","{'2019': {'year': 2019, 'value': 74438}, '2022...","{'2019': {'year': 2019, 'total': 733}, '2022':...","{'2002-08-26': {'event': 'Sale', 'date': '2002...","{'names': ['Joseph Luckmann'], 'mailingAddress...",1.0,NaN
1,"710-1-2-5th-Ave,-Sheldon,-IA-51201","710 1/2 5th Ave, Sheldon, IA 51201",710 1/2 5th Ave,None,Sheldon,IA,51201,Obrien,43.182338,-95.851360,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"10641-Jetrock-Dr,-El-Paso,-TX-79935","10641 Jetrock Dr, El Paso, TX 79935",10641 Jetrock Dr,None,El Paso,TX,79935,El Paso,31.787636,-106.329080,...,R4,1986-12-31T00:00:00.000Z,NaN,"{'architectureType': 'Duplex', 'cooling': True...","{'2018': {'year': 2018, 'value': 74879, 'land'...","{'2018': {'year': 2018, 'total': 2350}, '2022'...","{'1986-12-31': {'event': 'Sale', 'date': '1986...","{'names': ['Thomas M Lang', 'Gloria S Lang'], ...",0.0,NaN
3,"1915-W-67th-St,-Los-Angeles,-CA-90047","1915 W 67th St, Los Angeles, CA 90047",1915 W 67th St,None,Los Angeles,CA,90047,Los Angeles,33.978698,-118.311773,...,LAR1,2014-06-12T00:00:00.000Z,305000.0,"{'architectureType': 'Spanish', 'floorCount': ...","{'2019': {'year': 2019, 'value': 335165, 'land...","{'2019': {'year': 2019, 'total': 4210}, '2023'...","{'2014-06-12': {'event': 'Sale', 'date': '2014...","{'names': ['Oscar Salcedo', 'Sandra Salcedo'],...",1.0,NaN
4,"381-French-Rd,-Cold-Brook,-NY-13324","381 French Rd, Cold Brook, NY 13324",381 French Rd,None,Cold Brook,NY,13324,Hamilton,43.375863,-74.731001,...,NaN,2008-10-23T00:00:00.000Z,170000.0,NaN,NaN,NaN,"{'2008-10-23': {'event': 'Sale', 'date': '2008...",NaN,NaN,NaN

In [42]:
real_estate_df.columns

Index(['id', 'formattedAddress', 'addressLine1', 'addressLine2', 'city',
       'state', 'zipCode', 'county', 'latitude', 'longitude', 'propertyType',
       'bedrooms', 'bathrooms', 'squareFootage', 'lotSize', 'yearBuilt',
       'assessorID', 'legalDescription', 'subdivision', 'zoning',
       'lastSaleDate', 'lastSalePrice', 'features', 'taxAssessments',
       'propertyTaxes', 'history', 'owner', 'ownerOccupied', 'hoa'],
      dtype='object')